import {IProductView} from './product-view';

export const PRODUCTS_VIEWS: IProductView[] =
[{id:  'bike1',    colour: '',
frame: 0,
model: '',
wheel: 0, brand: 'Comanche', price: 8000, thumb_url: '/assets/images/thb/C-023-TOMAHAWK-19-SILVER.png'},
{id: 'bike2',    colour: '',
frame: 0,
model: '',
wheel: 0, brand: 'Comanche', price: 4000, thumb_url: '/assets/images/thb/C-008-RIO-GRANDE-M-21-STEEL.png'},
{id: 'bike3',    colour: '',
frame: 0,
model: '',
wheel: 0, brand: 'Bianchi', price: 4000, thumb_url: '/assets/images/thb/C-025-TOMAHAWK-DISC-2013-20.5-BLACK.png'},
{id: 'bike4',    colour: '',
frame: 0,
model: '',
wheel: 0, brand: 'Bianchi', price: 4000, thumb_url: '/assets/images/thb/C-008-RIO-GRANDE-M-21-STEEL.png'},
{id: 'bike5',    colour: '',
frame: 0,
model: '',
wheel: 0, brand: 'Ranger', price: 4000, thumb_url: '/assets/images/thb/C-027-TOMAHAWK-29-17.5-BLACK.png'},
{id: 'bike6',    colour: '',
frame: 0,
model: '',
wheel: 0, brand: 'Ranger', price: 4000, thumb_url: '/assets/images/thb/C-025-TOMAHAWK-DISC-2013-20.5-BLACK.png'},
{id: 'bike7',    colour: '',
frame: 0,
model: '',
wheel: 0, brand: 'Ranger', price: 4000, thumb_url: '/assets/images/thb/C-008-RIO-GRANDE-M-21-STEEL.png'},
{id: 'bike8',    colour: '',
frame: 0,
model: '',
wheel: 0, brand: 'Comanche', price: 4000, thumb_url: '/assets/images/thb/C-027-TOMAHAWK-29-17.5-BLACK.png'}];
